server:
  port: 9030
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable-intelligence-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  ai:
    model.chat: openai
    openai:
      api-key: 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
      # base-url: https://openrouter.ai/api
      chat:
        options:
          model: gpt-5.4
          temperature: 0.2
      embedding:
        options:
          model: qwen/qwen3-embedding-8b
