server:
  port: 9030
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable-intelligence-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  ai:
    model.chat: openai
    openai:
      api-key: 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
      # base-url: https://openrouter.ai/api
      chat:
        options:
          model: gpt-5.4
          temperature: 0.2
      embedding:
        options:
          model: qwen/qwen3-embedding-8b
